### ISSUE TITLE
dtheta is never 0

### ISSUE THREAD

**Issue by guilhembn** [ENACRobotique/FAT_2018#12]
Due to the scaling and the recentering of the dtheta (radians to word) sent by the teensy, the recieved theta is never 0 when it should.

**Comment by Fabien-B** [comment]
If it can help, in paparazzi, floating points numbers are converted in binary fixed point (int)
`#define BFP_OF_REAL(_vr,_frac) ((_vr)*(1<<(_frac)))`
`#define FLOAT_OF_BFP(_vbfp,_frac) ((float)(_vbfp)/(1<<(_frac)))`

avec _frac un entier fixé, qui est différent suivant les besoins.
dans ppzr, pour les angles, _frac = 12

**Comment by guilhembn** [comment]
Really good idea. It should give us just a little less than 10^-4 radians of precision, which is 0.007 degrees. This should be enough :stuck_out_tongue:

**Comment by guilhembn** [comment]
Fixed in fa949ff
