### ISSUE TITLE
[AI] Flush serial on AI start

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/FAT_2018#22]
On the first AI start, AI crash because of junk in serial buffer.

**Comment by Fabien-B** [comment]
Workaround : send a synchro byte at the beginning of each message ?

**Comment by guilhembn** [comment]
And thus escape all the other bytes and make the message non fixed in length... Could be a solution but lot of work.
I will first try to empty the serial before sending the RESET command.
